---
styleguide: sourcelevel/linters
engines:
  fixme:
    enabled: true
    channel: stable
  radon:
    enabled: true
    channel: latest
  bandit:
    enabled: true
    channel: latest
  pep8:
    enabled: true
    channel: latest
exclude_paths: []
